import EmailList from '@/components/EmailList';
import { messageList } from '@/data/messageList';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [messages, setMessages] = useState(messageList);

  return (
    <>
      <Head>
        <title>TrybeMail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="App">
        <header>
          <h1>TrybeMail</h1>
        </header>
        <main>
          <EmailList messages={messageList} />
        </main>
      </div>
    </>
  )
}
